name: BatesPortfolio

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - 'feat/*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Run build for PRs
        run: |
          npm ci
          npm run build
  deployment:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Deploy to S3
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install node modules
        run: npm ci
      - name: Build webapp
        run: npm run build
      - name: Deploy to S3
        run: |
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          export AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
          export AWS_REGION=$AWS_REGION
          aws s3 rm s3://bates-portfolio-s3 --recursive
          aws s3 cp ./dist/ s3://bates-portfolio-s3 --recursive
          aws cloudfront create-invalidation --distribution-id E229ACJX46CML2 --paths "/*"
    env:
      AWS_ACCESS_KEY: ${{ vars.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{vars.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{vars.AWS_REGION }}
